src/urls.py
import django
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path
from appdata.views import (
indexView, appendData, saveData
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", indexView, name = "indexView"),
    # path('get/ajax/validate/formid', checkFormId, name = "validate_formid"),
    path('appendData', appendData, name='appendData'),
    path('saveData', saveData, name='saveData'),
]

# if django.conf.settings.DEBUG:
#     urlpatterns += static (django.conf.settings.STATIC_URL,
#                            document_root=django.conf.settings.STATIC_ROOT)
#     urlpatterns += static (django.conf.settings.MEDIA_URL,
#                            document_root=django.conf.settings.MEDIA_ROOT)

appdata/models.py
from django.db import models

DROPDOWN1 = (
    ('ch', 'Choose'),
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
)

DROPDOWN2 = (
    ('ch', 'Choose'),
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
)


class Friend (models.Model):
    form_id = models.CharField (max_length=100, unique=True)
    drop_down_1 = models.CharField (max_length=3, choices=DROPDOWN1)
    drop_down_2 = models.CharField (max_length=3, choices=DROPDOWN2)
    check_box_1 = models.BooleanField ()
    Integer_box = models.IntegerField ()
    text_box = models.CharField (max_length=100, null=True, blank=True)
    dob = models.DateField (auto_now=False, auto_now_add=False)
    new_check_box_1 = models.BooleanField ()
    new_check_box_2 = models.BooleanField ()
    new_check_box_A = models.BooleanField ()
    new_check_box_B = models.BooleanField ()
    new_check_box_C = models.BooleanField ()
    new_check_box_D = models.BooleanField ()
    integerbox_A = models.IntegerField ()
    integerbox_B = models.IntegerField ()
    integerbox_C = models.IntegerField ()
    integerbox_D = models.IntegerField ()

    def __str__(self):
        return self.form_id

appdata/forms.py
from .models import Friend
from django import forms
import datetime


class DataForm (forms.ModelForm):
    dob = forms.DateField (
        label='What is your birth date?',
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget (years=range (1980, datetime.date.today ().year - 5))
    )

    def __init__(self, *args, **kwargs):
        super (DataForm, self).__init__ (*args, **kwargs)

        for name in self.fields.keys ():
            self.fields[name].widget.attrs.update ({
                'class': 'form-control',
            })

    class Meta:
        model = Friend
        fields = ("__all__")

appdata/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.core import serializers
from .forms import DataForm
from .models import Friend


def indexView(request):
    form = DataForm ()
    friends = Friend.objects.all ()
    return render (request, "index.html", {"form": form, "friends": friends})


def appendData(request):
    # request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        # get the form data
        form = DataForm (request.POST)
        # save the data and after fetch the object in instance
        if form.is_valid ():
            instance = form.save ()
            # serialize in new friend object in json
            ser_instance = serializers.serialize ('json', [instance, ])
            # send to client side.
            return JsonResponse ({"instance": ser_instance}, status=200)
        else:
            # some form errors occured.
            return JsonResponse ({"error": form.errors}, status=400)

    return JsonResponse ({"error": ""}, status=400)


def saveData(request):
    form = DataForm ()
    friends = Friend.objects.all ()

    if request.is_ajax ():
        form = DataForm (request.POST)
        print (request.POST)
        if form.is_valid ():
            form.save ()
            return JsonResponse ({
                'message': 'success'
            })

    return render (request, "index.html", {"form": form, "friends": friends})


# def checkFormId(request):
#     # request should be ajax and method should be GET.
#     if request.is_ajax and request.method == "GET":
#         # get the nick name from the client side.
#         form_id = request.GET.get ("form_id", None)
#         # check for the nick name in the database.
#         if Friend.objects.filter (form_id=form_id).exists ():
#             # if nick_name found return not valid new friend
#             return JsonResponse ({"valid": False}, status=200)
#         else:
#             # if nick_name not found, then user can create a new friend.
#             return JsonResponse ({"valid": True}, status=200)
#
#     return JsonResponse ({}, status=400)

appdata/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Django jQuery-Ajax Form</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        #dis_table{
          font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        #dis_table td, #dis_table th {
          border: 1px solid #ddd;
          padding: 8px;
        }

        #dis_table tr:nth-child(even){background-color: #f2f2f2;}

        #dis_table tr:hover {background-color: #ddd;}

        #dis_table th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #4CAF50;
          color: white;
        }
    </style>
</head>
<body class="bg-light">

    {% block content %}
    {% endblock content %}
   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="static/JS/main.js"></script>

</body>
</html>

appdata/templates/formsdata_page.html
{% load crispy_forms_filters %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'template.css' %}">
    
    <title>Ajax Django Form</title>
    <style>
        #tab-style {
          font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        #tab-style td, #tab-style th {
          border: 1px solid #ddd;
          padding: 8px;
        }
        
        #tab-style tr:nth-child(even){background-color: #f2f2f2;}
        
        #tab-style tr:hover {background-color: #ddd;}
        
        #tab-style th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #4CAF50;
          color: white;
        }
        </style>
</head>
<body class="bg-light">

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            
        <a class="navbar-brand " href="#">Navbar</a> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="test.html">View</a>
            </li>
            </ul>
        </div>

    </nav>

    <div class="container pt-4 col-3" style="margin-bottom: 40px;" id="main-container">
                                       
        <form method="POST" id="post-form" class="form-data-main">{% csrf_token %}     
            <h3 style="text-align: center;
                   text-decoration: underline;">AJAX DJANGO FORM</h3>
            <div class="container-form" id="dis-container-form">           
                {{ form|crispy }}
            </div>
            <input type="button" id="continue" class="btn btn-primary" value="Continue" />
        </form>
        <input type="submit" id="fin-submit" class="btn btn-secondary" value="SUBMIT" style="margin-top: 10px;" />
        
    </div> <!-- /.container -->

    <div class="display-container pt-4 col-12" style="display: none; margin-left: 10px; margin-right: 10px;" id="dis-container">
        <h3 style="text-align: center;
                   text-decoration: underline;">APPEND DATA DETAILS</h3>  
    <form action="" method="POST" id="dis-form"> {% csrf_token %}
        <table id="tab-style" style="margin-top: 40px;">
            <thead>
                <tr>
                    <th>Drop Down-1</th>
                    <th>Drop Down-2</th>
                    <th>Check Box</th>
                    <th>Interger Text</th>
                    <th>Text Box</th>
                    <th>New Check-1</th>
                    <th>New Check-1</th>
                    <th>New Check-A</th>
                    <th>New Check-B</th>
                    <th>New Check-C</th>
                    <th>New Check-D</th>
                    <th>Interger Text-A</th>
                    <th>Interger Text-B</th>
                    <th>Interger Text-C</th>
                    <th>Interger Text-D</th>

                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
        <button type="submit" id="confirm" class="btn btn-primary" style="margin-top: 30px;">CONFIRM</button>

    </form>
    </div>
   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- <script src="static/scripts/main.js"></script> -->

</body>
</html>

appdata/templates/index.html
{% extends "base.html" %}




{% block content %}
   
    <div class="container pt-10 col-10" style="margin-top: 40px;" id="main-container">
        <form method="POST" id="initial-form" class="form-data-main">
            <h3 style="text-align: center;
                   text-decoration: underline;">Django jQuery-Ajax Form</h3>

            <div class="row">
                {% csrf_token %}
<!--                <div class="container-form" id="dis-container-form">-->
                   {% for field in form %}
                <div class="form-group" style="margin-top: 20px">
                    <label class="col-12">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
            </div>

            <input type="submit" id="continue" class="btn btn-primary" value="Continue" style="margin-left: 30rem;"/>
        <form>
        <input type="button" id="fin-submit" class="btn btn-secondary" value="SUBMIT" style="    margin-top: 30px;
    display: flex; margin-bottom: 30px;
    border-radius: 15%;
    border-color: cornflowerblue;
    font-size: medium;" />
    </div>
    <hr />

    <div class="display-container pt-4 col-10" style="display: none; margin-left: 10px; margin-right: 10px;" id="dis-container">
        <h3 style="text-align: center;
                   text-decoration: underline;">APPEND DATA DETAILS</h3>
        <table class="table table-striped table-sm" id="dis_table">
            <thead>
                <tr>
                    <th>Form ID</th>
                    <th>Drop Down - 1</th>
                    <th>Drop Down - 2</th>
                    <th>Check Box</th>
                    <th>Integer Box</th>
                    <th>Text Box</th>
                    <th>DOB</th>
                    <th>New Check Box 1</th>
                    <th>New Check Box 2</th>
                    <th>New Check Box A</th>
                    <th>New Check Box B</th>
                    <th>New Check Box C</th>
                    <th>New Check Box D</th>
                    <th>Integer Box A</th>
                    <th>Integer Box B</th>
                    <th>Integer Box C</th>
                </tr>
            </thead>
            <tbody>
            {% for friend in friends %}
            <tr>
                <td>{{friend.form_id}}</td>
                <td>{{friend.drop_down_1}}</td>
                <td>{{friend.drop_down_2}}</td>
                <td>{{friend.check_box_1}}</td>
                <td>{{friend.Integer_box}}</td>
                <td>{{friend.text_box}}</td>
                <td>{{friend.dob | date:"Y-m-d"}}</td>
                <td>{{friend.new_check_box_1}}</td>
                <td>{{friend.new_check_box_2}}</td>
                <td>{{friend.new_check_box_A}}</td>
                <td>{{friend.new_check_box_B}}</td>
                <td>{{friend.new_check_box_C}}</td>
                <td>{{friend.new_check_box_D}}</td>
                <td>{{friend.integerbox_A}}</td>
                <td>{{friend.integerbox_B}}</td>
                <td>{{friend.integerbox_C}}</td>
                <td>{{friend.integerbox_D}}</td>
                <td><input id='delete' type="button" value="DELETE" style='font-size: x-small;font-weight: bold;text-decoration: underline';/></td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
        <input type="submit" id="confirm" class="btn btn-primary" value="CONFIRM" style="margin-left: 30rem;"/>
<!--        <button type="submit" id="confirm" class="btn btn-primary" style="margin-top: 30px;">CONFIRM</button>-->
    </div>
{% endblock content %}

appdata/templates/initial_page.html
{% extends "base.html" %}
{% block style %}
<style>
    #tab-style {
      font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    #tab-style td, #tab-style th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #tab-style tr:nth-child(even){background-color: #f2f2f2;}
    
    #tab-style tr:hover {background-color: #ddd;}
    
    #tab-style th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #4CAF50;
      color: white;
    }
</style>
{% endblock style %}
{% block content %}
   
    <div class="container-fluid">
        <form id="initial-form">
            <div class="row">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group col-4">
                    <label class="col-12">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Continue" />
            </div>
        <form>
    </div>
    <hr />

    <div class="container-fluid">
        <table class="table table-striped table-sm" id="dis-table">
            <thead>
                <tr>
                    <th>Form ID</th>
                    <th>Drop Down - 1</th>
                    <th>Drop Down - 2</th>
                    <th>Check Box</th>
                    <th>Integer Box</th>
                    <th>Text Box</th>
                    <th>DOB</th>
                    <th>New Check Box 1</th>
                    <th>New Check Box 2</th>
                    <th>New Check Box A</th>
                    <th>New Check Box B</th>
                    <th>New Check Box C</th>
                    <th>New Check Box D</th>
                    <th>Integer Box A</th>
                    <th>Integer Box B</th>
                    <th>Integer Box C</th>
                    <th>Integer Box D</th>
                </tr>
            </thead>
            <tbody>
            {% for friend in friends %}
            <tr>
                <td>{{friend.form_id}}</td>
                <td>{{friend.dropdown1}}</td>
                <td>{{friend.dropdown2}}</td>
                <td>{{friend.checkbox1}}</td>
                <td>{{friend.Integerbox}}</td>
                <td>{{friend.textbox}}</td>
                <td>{{friend.dob | date:"Y-m-d"}}</td>
                <td>{{friend.newcheckbox1}}</td>
                <td>{{friend.newcheckbox2}}</td>
                <td>{{friend.newcheckboxA}}</td>
                <td>{{friend.newcheckboxB}}</td>
                <td>{{friend.newcheckboxC}}</td>
                <td>{{friend.newcheckboxD}}</td>
                <td>{{friend.IntegertextA}}</td>
                <td>{{friend.IntegertextB}}</td>
                <td>{{friend.IntegertextC}}</td>
                <td>{{friend.IntegertextD}}</td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    
    </div>
{% endblock content %}

{% block javascript %}
<script>
    /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
    */
    $("#initial-form").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();
        // make POST ajax call
        $.ajax({
            type: 'POST',
            url: "{% url 'appendData' %}",
            data: serializedData,
            success: function (response) {
                // on successfull creating object
                // 1. clear the form.
                $("#initial-form").trigger('reset');
                // 2. focus to nickname input 
                $("#id_dropdown").focus();

                // display the newly friend to table.
                var instance = JSON.parse(response["instance"]);
                var fields = instance[0]["fields"];
                $("#dis-table tbody").prepend(
                    `<tr>
                    <td>${fields["form_id"]||""}</td>
                    <td>${fields["dropdown1"]||""}</td>
                    <td>${fields["dropdown2"]||""}</td>
                    <td>${fields["checkbox1"]||""}</td>
                    <td>${fields["Integerbox"]||""}</td>
                    <td>${fields["textbox"]||""}</td>
                    <td>${fields["dob"]||""}</td>
                    <td>${fields["newcheckbox1"]||""}</td>
                    <td>${fields["newcheckbox2"]||""}</td>
                    <td>${fields["newcheckboxA"]||""}</td>
                    <td>${fields["newcheckboxB"]||""}</td>
                    <td>${fields["newcheckboxC"]||""}</td>
                    <td>${fields["newcheckboxD"]||""}</td>
                    <td>${fields["IntegertextA"]||""}</td>
                    <td>${fields["IntegertextB"]||""}</td>
                    <td>${fields["IntegertextC"]||""}</td>
                    <td>${fields["IntegertextD"]||""}</td>

                    </tr>`
                )
            },
            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        })
    })
    $("#id_form_id").focusout(function (e) {
        e.preventDefault();
        // get the nickname
        var form_id = $(this).val();
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: "{% url 'validate_formid' %}",
            data: {"form_id": fom_id},
            success: function (response) {
                // if not valid user, alert the user
                if(!response["valid"]){
                    alert("You cannot create a friend with same nick name");
                    var formid = $("#id_form_id");
                    formid.val("")
                    formid.focus()
                }
            },
            error: function (response) {
                console.log(response)
            }
        })
    })
</script>
{% endblock javascript %}